save_folder: data
year_split: 2020
experiment_name_load: may
experiment_name_save: 'test'
riskless_rate: 0.03

data_folder: "data/ticker_data_preprocessed_${experiment_name_load}.csv"
ticker_data_sp500: "data/ticker_data_SP500_${experiment_name_load}.csv"
save_path: ${save_folder}/embeddings_${year_split}_${experiment_name_save}

emb_size: 100
random_state: 42

embedding_methods:
  - FastICA:
      _target_: embeddings.base_embedding.ClassicEmbedding
      emb_model:
        _target_: sklearn.decomposition.FastICA
        n_components: ${emb_size}
        random_state: ${random_state}
      path: ${save_path}/fastica.csv
  - UMAP:
      _target_: embeddings.base_embedding.ClassicEmbedding
      emb_model:
        _target_: umap.UMAP
        n_components: ${emb_size}
        random_state: ${random_state}
      path: ${save_path}/umap.csv

  - PCA:
      _target_: embeddings.base_embedding.ClassicEmbedding
      emb_model:
        _target_: sklearn.decomposition.PCA
        n_components: ${emb_size}
        random_state: ${random_state}
      path: ${save_path}/pca.csv

  - Autoencoders_MLP:
      _target_: embeddings.base_embedding.AutoencoderEmbedding
      model_name : mlp
      model_params:
        checkpoint_path: "autoencoders/lightning_logs_2020/mlp/version_0/checkpoints/epoch=149-step=15450.ckpt"
        in_features: ${emb_size}
        latent_features: ${emb_size}
      path: ${save_path}/autoencoder_mlp.csv

  - Autoencoders_CNN:
      _target_: embeddings.base_embedding.AutoencoderEmbedding
      model_name : cnn
      model_params:
        checkpoint_path: "autoencoders/lightning_logs_2020/cae/version_0/checkpoints/epoch=99-step=10300.ckpt"
        in_channels: 1
        n_latent_features: ${emb_size}
        seq_len: ${emb_size}
      path: ${save_path}/autoencoder_conv.csv

  - Autoencoders_LSTM:
      _target_: embeddings.base_embedding.AutoencoderEmbedding
      model_name : lstm
      model_params:
        checkpoint_path: "autoencoders/lightning_logs_2020/lstm/version_0/checkpoints/epoch=99-step=9100.ckpt"
        seq_len: ${emb_size}
        n_features: 1
        embedding_dim: ${emb_size}
      path:  ${save_path}/autoencoder_lstm.csv

  - Table_finance:
      _target_: embeddings.base_embedding.FinancialMetricEmbedding
      riskless_rate: ${riskless_rate}
      path:  ${save_path}/table_finance_features.csv

  - TSFresh:
      _target_: embeddings.base_embedding.TSFreshEmbedding
      n_features: ${emb_size}
      path:  ${save_path}/tsfresh.csv

  - TS2Vec:
      _target_: embeddings.base_embedding.TS2VecEmbedding
      emb_model: 
        _target_: ts2vec.ts2vec.TS2Vec
        input_dims: 1
        device: 0
        output_dims: 100
      path: ${save_path}/ts2vec.csv

  
