riskless_rate: 0.03
ret_det: 0.03
n_clusters: 11
n_stock_portfolio: 2
random_state: 42
year_split: 2020
year_end: 2023
fine_tune: False
experiment_name: 'usa_2018'
sectors_path: "data/tickers_list/sp500_ticker_sectors.csv"

save_path: results/${experiment_name}
load_path: data/data/${experiment_name}
data_path: "${load_path}/ticker_data_preprocessed.csv"
market_path: "${load_path}/ticker_data_Market.csv"

embedding_path: 'data/embeddings/${experiment_name}'

clust_models:
  KMeans: 
    _target_: sklearn.cluster.KMeans   
    n_clusters: ${n_clusters}
    random_state: ${random_state}
  Agg:
    _target_: sklearn.cluster.AgglomerativeClustering   
    n_clusters: ${n_clusters}

clust_models_params:
  KMeans: 
    n_clusters: [9, 10, 11, 12, 13]
    init: ['k-means++', 'random']
    algorithm: ['auto', 'full', 'elkan']
  Agg: 
    n_clusters: [9, 10, 11, 12, 13]
    linkage': ['ward', 'complete', 'average', 'single']


clust_params:
  make_grid: ${fine_tune} 

selection_params:
  n_save: ${n_stock_portfolio}
  riskfree_rate: ${riskless_rate}


backtesting_params:
  window_train: 24 # size of train window in months
  window_test: 1  # size of train window in months   
  test_start_year: ${year_split} #start data year
  test_start_month: 1 #start data month 
  test_finish_year: ${year_end} #end data year
  test_finish_month: 1 #end data month


financial_metric_path: "${save_path}/financial_metric_${fine_tune}.csv"
clust_metric_path: "${save_path}/clust_metric_${fine_tune}.csv"
port_path: "${save_path}/metrics_table_${fine_tune}.pickle"
weights_path: "${save_path}/weights_table_${fine_tune}.pickle"